### ISSUE TITLE
`scripts/build.sh` should be executed during `docker build` rather than `docker run`

### ISSUE THREAD

**Issue by AkihiroSuda** [yomaytk/elfconv#38]
Is there any reason to omit `scripts/build.sh` from the Dockerfile's `RUN` steps?

**Comment by AkihiroSuda** [comment]
I also suggest to remove integration tests from the default `ENTRYPOINT` script, as it takes more than 10 minutes.

**Comment by yomaytk** [comment]
Thank you for your suggestion!

> Is there any reason to omit scripts/build.sh from the Dockerfile's RUN steps?
> I also suggest to remove integration tests from the default ENTRYPOINT script, as it takes more than 10 minutes.

As you say, it would be better to run `scripts/build.sh` during container image build, and to separate the integration test from the `ENTRYPOINT`. Thanks.
