### ISSUE TITLE
Error: failed to run main module `exe.wasm`

### ISSUE THREAD

**Issue by LeeJU0912** [yomaytk/elfconv#68]
I am struggling with this error while following Quick Start.
```bash
~/elfconv/bin# wasmtime exe.wasm

Error: failed to run main module `exe.wasm`

Caused by:
    0: failed to instantiate "exe.wasm"
    1: unknown import: `env::__syscall_readlinkat` has not been defined
```

I built container on CentOS7(amd64) and just followed instructions at `Quickstart - Host (WASI runtimes)`

**Comment by yomaytk** [comment]
@LeeJU0912 
I fixed this bug by https://github.com/yomaytk/elfconv/pull/70, so I think it will work correctly in the latest commit.

**Comment by LeeJU0912** [comment]
Thank you!! I can check on tomorrow morning. I'll test and let you know. :)

**Comment by LeeJU0912** [comment]
It works fine! Thank you :)

**Comment by yomaytk** [comment]
The issue was resolved, so I will close it. Thanks for the report and please feel free to file new one if needed.
